Make DB downloads idempotent, contained in 'out/' directory

diff --git a/tools/ci_download_cockroachdb b/tools/ci_download_cockroachdb
--- a/tools/ci_download_cockroachdb
+++ b/tools/ci_download_cockroachdb
@@ -7,7 +7,6 @@
 #
 
 set -o pipefail
-set -o xtrace
 set -o errexit
 
 SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
@@ -17,7 +16,11 @@ ARG0="$(basename ${BASH_SOURCE[0]})"
 CIDL_VERSION="$(cat "$SOURCE_DIR/cockroachdb_version")"
 source "$SOURCE_DIR/cockroachdb_checksums"
 
-CIDL_ASSEMBLE_DIR="./cockroachdb"
+TARGET_DIR="out"
+# Location where intermediate artifacts are downloaded / unpacked.
+DOWNLOAD_DIR="$TARGET_DIR/downloads"
+# Location where the final cockroachdb directory should end up.
+DEST_DIR="./$TARGET_DIR/cockroachdb"
 
 # Official (or unofficial) download sites
 CIDL_URL_COCKROACH="https://binaries.cockroachdb.com"
@@ -25,113 +28,133 @@ CIDL_URL_ILLUMOS="https://illumos.org/downloads"
 
 function main
 {
-	#
-	# Process command-line arguments.  We generally don't expect any, but
-	# we allow callers to specify a value to override OSTYPE, just for
-	# testing.
-	#
-	if [[ $# != 0 ]]; then
-		CIDL_OS="$1"
-		shift
-	else
-		CIDL_OS="$OSTYPE"
-	fi
+  #
+  # Process command-line arguments.  We generally don't expect any, but
+  # we allow callers to specify a value to override OSTYPE, just for
+  # testing.
+  #
+  if [[ $# != 0 ]]; then
+    CIDL_OS="$1"
+    shift
+  else
+    CIDL_OS="$OSTYPE"
+  fi
 
-	if [[ $# != 0 ]]; then
-		echo "unexpected arguments" >&2
-		exit 2
-	fi
+  if [[ $# != 0 ]]; then
+    echo "unexpected arguments" >&2
+    exit 2
+  fi
 
-	# Configure this program
-	configure_os "$CIDL_OS"
-	CIDL_URL="$CIDL_URL_BASE/$CIDL_FILE"
+  # Configure this program
+  configure_os "$CIDL_OS"
+  CIDL_URL="$CIDL_URL_BASE/$TARBALL_FILENAME"
 
-	# Download the file.
-	echo "URL: $CIDL_URL"
-	echo "Local file: $CIDL_FILE"
-	do_download_curl "$CIDL_URL" "$CIDL_FILE" || \
-	    fail "failed to download file"
+  # Download the file.
+  echo "URL: $CIDL_URL"
+  echo "Local file: $TARBALL_FILE"
 
-	# Verify the md5sum.
-	calculated_md5="$($CIDL_MD5FUNC "$CIDL_FILE")" || \
-	    fail "failed to calculate md5sum"
-	if [[ "$calculated_md5" != "$CIDL_MD5" ]]; then
-		fail "md5sum mismatch \
-		    (expected $CIDL_MD5, found $calculated_md5)"
-	fi
+  mkdir -p "$DOWNLOAD_DIR"
+  mkdir -p "$DEST_DIR"
 
-	# Unpack the tarball.
-	do_untar "$CIDL_FILE"
+  local DO_DOWNLOAD="true"
+  if [[ -f "$TARBALL_FILE" ]]; then
+    # If the file exists with a valid checksum, we can skip downloading.
+    calculated_md5="$($CIDL_MD5FUNC "$TARBALL_FILE")" || \
+        fail "failed to calculate md5sum"
+    if [[ "$calculated_md5" == "$CIDL_MD5" ]]; then
+      DO_DOWNLOAD="false"
+    fi
+  fi
 
-	# Copy the "cockroach" binary to the right spot.
-	$CIDL_ASSEMBLE "$CIDL_DIR"
+  if [ "$DO_DOWNLOAD" == "true" ]; then
+    echo "Downloading..."
+    do_download_curl "$CIDL_URL" "$TARBALL_FILE" || \
+        fail "failed to download file"
 
-	# Run the binary as a sanity-check.
-	"$CIDL_ASSEMBLE_DIR/bin/cockroach" version
+    # Verify the md5sum.
+    calculated_md5="$($CIDL_MD5FUNC "$TARBALL_FILE")" || \
+        fail "failed to calculate md5sum"
+    if [[ "$calculated_md5" != "$CIDL_MD5" ]]; then
+      fail "md5sum mismatch \
+          (expected $CIDL_MD5, found $calculated_md5)"
+    fi
+  fi
+
+  # Unpack the tarball.
+  do_untar "$TARBALL_FILE"
+
+  # Copy the "cockroach" binary to the right spot.
+  $CIDL_ASSEMBLE
+
+  # Run the binary as a sanity-check.
+  "$DEST_DIR/bin/cockroach" version
 }
 
 function fail
 {
-	echo "$ARG0: $@" >&2
-	exit 1
+  echo "$ARG0: $@" >&2
+  exit 1
 }
 
 function configure_os
 {
-	echo "current directory: $PWD"
-	echo "configuring based on OS: \"$1\""
-	case "$1" in
-		darwin*)
-			CIDL_BUILD="darwin-10.9-amd64"
-			CIDL_SUFFIX="tgz"
-			CIDL_MD5="$CIDL_MD5_DARWIN"
-			CIDL_MD5FUNC="do_md5"
-			CIDL_URL_BASE="$CIDL_URL_COCKROACH"
-			CIDL_ASSEMBLE="do_assemble_official"
-			;;
-		linux-gnu*) 
-			CIDL_BUILD="linux-amd64"
-			CIDL_SUFFIX="tgz"
-			CIDL_MD5="$CIDL_MD5_LINUX"
-			CIDL_MD5FUNC="do_md5sum"
-			CIDL_URL_BASE="$CIDL_URL_COCKROACH"
-			CIDL_ASSEMBLE="do_assemble_official"
-			;;
-		solaris*)
-			CIDL_BUILD="illumos"
-			CIDL_SUFFIX="tar.gz"
-			CIDL_MD5="$CIDL_MD5_ILLUMOS"
-			CIDL_MD5FUNC="do_md5sum"
-			CIDL_URL_BASE="$CIDL_URL_ILLUMOS"
-			CIDL_ASSEMBLE="do_assemble_illumos"
-			;;
-		*)
-			fail "unsupported OS: $1"
-			;;
-	esac
+  echo "current directory: $PWD"
+  echo "configuring based on OS: \"$1\""
+  case "$1" in
+    darwin*)
+      CIDL_BUILD="darwin-10.9-amd64"
+      CIDL_SUFFIX="tgz"
+      CIDL_MD5="$CIDL_MD5_DARWIN"
+      CIDL_MD5FUNC="do_md5"
+      CIDL_URL_BASE="$CIDL_URL_COCKROACH"
+      CIDL_ASSEMBLE="do_assemble_official"
+      ;;
+    linux-gnu*)
+      CIDL_BUILD="linux-amd64"
+      CIDL_SUFFIX="tgz"
+      CIDL_MD5="$CIDL_MD5_LINUX"
+      CIDL_MD5FUNC="do_md5sum"
+      CIDL_URL_BASE="$CIDL_URL_COCKROACH"
+      CIDL_ASSEMBLE="do_assemble_official"
+      ;;
+    solaris*)
+      CIDL_BUILD="illumos"
+      CIDL_SUFFIX="tar.gz"
+      CIDL_MD5="$CIDL_MD5_ILLUMOS"
+      CIDL_MD5FUNC="do_md5sum"
+      CIDL_URL_BASE="$CIDL_URL_ILLUMOS"
+      CIDL_ASSEMBLE="do_assemble_illumos"
+      ;;
+    *)
+      fail "unsupported OS: $1"
+      ;;
+  esac
 
-	CIDL_DIR="cockroach-$CIDL_VERSION.$CIDL_BUILD"
-	CIDL_FILE="$CIDL_DIR.$CIDL_SUFFIX"
+  TARBALL_DIRNAME="cockroach-$CIDL_VERSION.$CIDL_BUILD"
+  TARBALL_FILENAME="$TARBALL_DIRNAME.$CIDL_SUFFIX"
+
+  TARBALL_FILE="$DOWNLOAD_DIR/$TARBALL_FILENAME"
+  TARBALL_DIR="$DOWNLOAD_DIR/$TARBALL_DIRNAME"
 }
 
 function do_download_curl
 {
-	curl --silent --show-error --fail --location --output "$2" "$1"
+  curl --silent --show-error --fail --location --output "$2" "$1"
 }
 
 function do_md5
 {
-	md5 < "$1"
+  md5 < "$1"
 }
 
 function do_md5sum
 {
-	md5sum < "$1" | awk '{print $1}'
+  md5sum < "$1" | awk '{print $1}'
 }
 
 function do_untar
 {
-	tar xzf "$1"
+  tar xzf "$1" -C "$DOWNLOAD_DIR"
 }
 
 #
@@ -145,14 +168,14 @@ function do_untar
 
 function do_assemble_official
 {
-	mkdir -p "$CIDL_ASSEMBLE_DIR/bin"
-	cp "$CIDL_DIR/cockroach" "$CIDL_ASSEMBLE_DIR/bin"
+  mkdir -p "$DEST_DIR/bin"
+  cp "$TARBALL_DIR/cockroach" "$DEST_DIR/bin"
 }
 
 function do_assemble_illumos
 {
-	rm -r "$CIDL_ASSEMBLE_DIR" || true
-	cp -r "cockroach-$CIDL_VERSION" "$CIDL_ASSEMBLE_DIR"
+  rm -r "$DEST_DIR" || true
+  cp -r "$DOWNLOAD_DIR/cockroach-$CIDL_VERSION" "$DEST_DIR"
 }
 
 main "$@"
